### ISSUE TITLE
Material-ui Theme

### ISSUE THREAD

**Issue by ahmetcaglayan** [ranjanrajiv00/micro-frontends#1]
add material-ui and theme?
I have a hard time solving it because there are so many problems.

**Comment by ahmetcaglayan** [comment]
also needs to be removed in common packages.

added webpack externals react, material-ui

**Comment by leocristofani** [comment]
Good morning Ahmet. Thanks for your interest in this project! But just to be clear, this is not meant to be a starter project, but more of a reference to micro-frontends. This repo is supporting code for this article https://www.scalablepath.com/blog/.
